print("\n****** Different types of using range ******")
r = range(5)
print(r)
print("Range with one parameter ",list(r))
print("\n")
r1 = range(1,5)
print(r1)
print("Range with two parameter r1",list(r1))
print("\n")
r2 = range(1,10,2)
print(r2)
print("Range with two parameter r2",list(r2))
